### ISSUE TITLE
Auto-generate RUM data

### ISSUE THREAD

**Issue by stevedatadog** [DataDog/ecommerce-workshop#155]
Script a headless browser to interact with the Storedog UI.  Perhaps part of the traffic container? Selenium, PhantomJS, etc.

**Comment by stevedatadog** [comment]
@obensource and @ryanmaclean are working on a solution using puppeteer.

**Comment by stevedatadog** [comment]
We have a solution for this that uses a 3rd party docker image and two custom scripts. The container will run `puppeteer.sh`, which in turn runs`node puppeteer.js` in an infinite loop. `puppeteer.js` clicks on a bunch of Storedog UI selectors across multiple pages:  
```
 puppeteer:
    image: buildkite/puppeteer:10.0.0
    volumes:
      - /root/puppeteer-mobile.js:/puppeteer.js
      - /root/puppeteer.sh:/puppeteer.sh
    environment: 
      - RUM_START_URL
    depends_on:
      - frontend
    command: bash puppeteer.sh
```
This is probably not general-purpose enough to add by default to the stack, but it's a good starting point for a flexible solution.
